- name: Run Kafka Debugger
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_broker | default('localhost') }}"
        port: "{{ kafka_port | default(9092) }}"
        topics:
          - eda

  rules:
    - name: "When a message is received on topic 'eda', print its content"
      condition: event.topic == "eda"
      actions:
        run_job_template:
          name: Print the message content
          organization: CaC
          job_args:
            extra_vars:
              message: "{{ event.value }}"
              event_headers: "{{ event.headers }}"
              event_key: "{{ event.key }}"
              event_partition: "{{ event.partition }}"
              event_offset: "{{ event.offset }}"
              event_timestamp: "{{ event.timestamp }}"
              event_topic: "{{ event.topic }}"
