---

- name: Run Kafka Debugger
  hosts: localhost
  sources:
    - ansible.eda.kafka:
        host: "{{ kafka_broker | default('localhost') }}"
        port: "{{ kafka_port | default(9092) }}"
        topics:
          - "eda"

  rules:
    - name: "When a message is received on topic 'eda', print its content"
      condition: event.topic == "eda"
      actions:
        - debug:
            msg: "Received message on topic 'eda': {{ event.value }}"
